FROM webdevops/php-nginx:8.1

WORKDIR /app

# by creating a project in, it means we only have to 'manage' our changes
# but it does mean we have to rebuild each time
RUN composer create-project laravel/laravel . "10.*" --prefer-dist
RUN composer require orchid/platform
RUN composer require orchid/crud
RUN php artisan orchid:install

COPY root/ /
COPY --chown=application:application src /app

RUN echo upload_max_filesize=40M >> /opt/docker/etc/php/php.ini
RUN echo post_max_size=40M >> /opt/docker/etc/php/php.ini
RUN chmod -R 0777 /app/bootstrap
RUN mkdir -m 0755 -p /app/storage && \
    mkdir -m 0755 -p /app/storage/app && \
    mkdir -m 0755 -p /app/storage/framework && \
    mkdir -m 0755 -p /app/storage/logs && \
    mkdir -m 0755 -p /app/storage/framework/cache && \
    mkdir -m 0755 -p /app/storage/framework/sessions && \
    mkdir -m 0755 -p /app/storage/framework/views

RUN chown -R application:application /app/storage

# makes admin account
# RUN php artisan orchid:admin terrykernan terry@terrykernan.co.uk LetMeIn

# publishes assets into public folder from vendor folder
RUN php artisan orchid:publish

EXPOSE 80